# Generated by Django 3.0.6 on 2020-09-07 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csvApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validate',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='validate', serialize=False, to='csvApp.Document')),
                ('names_list', models.TextField()),
                ('csv_list', models.TextField()),
            ],
        ),
    ]
